"""empty message

Revision ID: 358bebf94826
Revises: 94ff84517120
Create Date: 2017-03-27 18:35:17.676811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '358bebf94826'
down_revision = '94ff84517120'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('member_since', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'member_since')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###
